version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Building NGINX
      - mkdir -p /var/www/html/
      - cp ./index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - nginx -t || echo "NGINX configuration test failed"
      - nginx

artifacts:
  files:
  - '**/*'