version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
      - echo Building NGINX
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX
      - systemctl restart nginx

artifacts:
  files:
    - '**/*'
